# Image settings
image:
  repository: containers.github.grnoc.iu.edu/ndca/tsds-services
  pullPolicy: IfNotPresent
  tag: "1.7.2-dev" # Overrides the image tag whose default is the chart appVersion.
  
imagePullSecrets: 
 - name: julius-github

aggregate:
  image:
    repository: containers.github.grnoc.iu.edu/ndca/tsds-aggregate
    tag: "1.2.2-dev"
    
frontend:
  image:
    repository: containers.github.grnoc.iu.edu/ndca/tsds-frontend
    tag: "1.0.0-dev"

# nameservice urls:
cdsUrl: https://db2.grnoc.iu.edu
tixUrl: https://sn-tools.grnoc.iu.edu

# LDAP group to access tsds (frontend & backend)
ldapGroup: cn=snapp-admin,ou=webapps,dc=grnoc,dc=iu,dc=edu

# Deployment/Stateful Set Replica Counts
replicaCount:
  aggregateWorkers: 1
  aggregateWriters: 1
  apache: 1
  memcached: 1
  mongodb: 3
  arbiters: 1
  rabbitmq: 1
  redis: 3
  sphinx: 1
  writers: 1

globalnoc-shib:
  globalnoc:
    tool: "tsds"
    hostname: "tsds"
  nameOverride: "tsds-shib"
  apacheConfigMap: tsds-apache-shib

global:
  ldapURL: "foobar"