#!/bin/bash

sudo systemctl daemon-reload;
sudo systemctl stop grafana-server;
sudo systemctl stop vce;
sudo systemctl stop tsds_writer;
sudo systemctl stop searchd;
sudo systemctl stop memcached;
sudo systemctl stop mongos;
sudo systemctl stop mongod-shard1;
sudo systemctl stop mongod-config1;
sudo systemctl stop simp-poller;
sudo systemctl stop simp-tsds;
sudo systemctl stop simp-comp;
sudo systemctl stop simp-data;
sudo systemctl stop redis;
sudo systemctl stop httpd;
sudo systemctl stop rabbitmq-server;

sudo rm -rf /var/lib/mongo/config1/*
sudo rm -rf /var/lib/mongo/shard1/*
# sudo rm /usr/share/perl5/vendor_perl/GRNOC/TSDS.pm
# sudo rm /usr/share/perl5/vendor_perl/GRNOC/TSDS
make clean && clear && perl Makefile.PL && make rpm
sudo yum remove -y grnoc-tsds-services.noarch
sudo yum remove mongodb-org -y
sudo yum remove sphinx -y
sudo yum install -y /home/absheth/rpmbuild/RPMS/noarch/grnoc-tsds-services-1.6.2-4.el7.noarch.rpm
# Only for testing -- Start
# sudo rm /usr/share/perl5/vendor_perl/GRNOC/TSDS.pm
# sudo rm -rf /usr/share/perl5/vendor_perl/GRNOC/TSDS
# sudo ln -sf /home/absheth/tsds-services/lib/GRNOC/TSDS.pm /usr/share/perl5/vendor_perl/GRNOC/TSDS.pm
# sudo ln -sf /home/absheth/tsds-services/lib/GRNOC/TSDS /usr/share/perl5/vendor_perl/GRNOC/TSDS
# Only for testing -- End
sudo systemctl stop grafana-server;
sudo systemctl stop vce;
sudo systemctl stop tsds_writer;
sudo systemctl stop searchd;
sudo systemctl stop memcached;
sudo systemctl stop mongos;
sudo systemctl stop mongod-shard1;
sudo systemctl stop mongod-config1;
sudo systemctl stop simp-poller;
sudo systemctl stop simp-tsds;
sudo systemctl stop simp-comp;
sudo systemctl stop simp-data;
sudo systemctl stop redis;
sudo systemctl stop httpd;
sudo systemctl stop rabbitmq-server;


# sudo /usr/bin/tsds_setup.pl
# sudo systemctl daemon-reload;
# sudo systemctl restart rabbitmq-server;
# sudo systemctl restart redis;
# sudo systemctl restart vce;
# sudo systemctl restart httpd;
# sudo systemctl restart simp-data;
# sudo systemctl restart simp-comp;
# sudo systemctl restart simp-poller;
# sudo systemctl restart mongos;
# sudo systemctl restart mongod-config1;
# sudo systemctl restart mongod-shard1;
# sudo systemctl restart simp-tsds;
# sudo systemctl restart memcached;
# sudo systemctl restart searchd; 
# sudo systemctl restart tsds_writer;
# sudo systemctl restart grafana-server;
