---
apiVersion: v1
kind: Service
metadata:
  name: tsds-memcached
  labels:
    {{ include "tsds.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 11211
      targetPort: 11211
      name: tsds-memcached
  selector:
    app: tsds-memcached
