---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: tsds-mongodb
  labels:
    app: tsds-mongodb
spec:
  members: {{ .Values.replicaCount.mongodb | default 1 }}
  arbiters: {{ .Values.replicaCount.arbiters | default 1 }}
  type: ReplicaSet
  version: "4.2.0"
  security:
    authentication:
      ignoreUnknownUsers: true
      modes: ["SCRAM", "SCRAM-SHA-1"]
  users:
    - db: admin
      name: root
      passwordSecretRef:
        name: tsds-mongodb-root-password
      roles:
        - db: admin
          name: root
      scramCredentialsSecretName: tsds-mongodb-root-scram
