---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: tsds-mongodb
  labels:
    app: tsds-mongodb
spec:
  statefulSet:
    spec:
      selector:
          matchLabels:
            {{- include "mongodb.selectorLabels" . | nindent 12 }}
      template:
        metadata:
          # label the pod which is used by the "labelSelector" in podAntiAffinty
          # you can label it witch some other labels as well -- make sure it change the podAntiAffinity labelselector accordingly
          labels:
          app.kubernetes.io/name: 
            {{- include "mongodb.selectorLabels" . | nindent 12 }}
        spec:
          {{- with .Values.mongodb.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          {{- with .Values.mongodb.topologySpreadConstraints }}
          topologySpreadConstraints:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          {{- with .Values.mongodb.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: {{ .Values.mongodb.limits.cpu | default "'5'" }}
                  memory: {{ .Values.mongodb.limits.memory | default "5000M" }}
                requests:
                  cpu: {{ .Values.mongodb.requests.cpu | default "'2'" }}
                  memory: {{ .Values.mongodb.requests.memory | default "1000M" }}
  members: {{ .Values.replicaCount.mongodb | default 1 }}
  arbiters: {{ .Values.replicaCount.arbiters | default 1 }}
  type: ReplicaSet
  version: "4.2.0"
  security:
    authentication:
      ignoreUnknownUsers: true
      modes: ["SCRAM", "SCRAM-SHA-1"]
  users:
    - db: admin
      name: root
      passwordSecretRef:
        name: tsds-mongodb-root-password
      roles:
        - db: admin
          name: root
      scramCredentialsSecretName: tsds-mongodb-root-scram
