apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: tsds-rabbitmq
  labels:
    app: tsds-rabbitmq
spec:
  rabbitmq:
    additionalConfig: |
      loopback_users = none
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_shovel
      - rabbitmq_shovel_management
      - rabbitmq_top
  replicas: {{ .Values.replicaCount.rabbitmq }}
  resources:
    requests:
      cpu: {{ .Values.rabbitmq.requests.cpu | default "'1'" }}
      memory: {{ .Values.rabbitmq.requests.memory | default "2Gi" }}
    limits:
      cpu: {{ .Values.rabbitmq.limits.cpu | default "'1'" }}
      memory: {{ .Values.rabbitmq.limits.memory | default "2Gi" }}
