apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: tsds-rabbitmq
  labels:
    app: tsds-rabbitmq
spec:
  rabbitmq:
    additionalConfig: |
      loopback_users = none
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_shovel
      - rabbitmq_shovel_management
      - rabbitmq_top
  replicas: {{ .Values.rabbitmq.replicaCount }}
  {{- with .Values.rabbitmq.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
