---
apiVersion: v1
kind: Service
metadata:
  name: tsds-redis
  labels:
    {{ include "tsds.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: tsds-redis
  selector:
    app: tsds-redis
