---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tsds-redis-config
  labels:
    {{ include "tsds.labels" . | nindent 4 }}
data:
  redis.conf: |
    bind 0.0.0.0
    unixsocket /var/run/redis/redis.sock
    unixsocketperm 777
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis/redis.pid
    loglevel notice
    logfile /var/log/redis/redis.log
    databases 16
    save ""
    dir /var/lib/redis
    protected-mode yes
    repl-diskless-sync no
    repl-diskless-sync-delay 5
    repl-disable-tcp-nodelay no
    slave-priority 100
    appendonly no
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite yes
    auto-aof-rewrite-percentage 0
    aof-load-truncated yes
    lua-time-limit 0
    slowlog-log-slower-than 50000
    slowlog-max-len 1024
    latency-monitor-threshold 0
    notify-keyspace-events ""
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    activerehashing no
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit slave  0 0 0
    client-output-buffer-limit pubsub 0 0 0
    hz 100
    aof-rewrite-incremental-fsync yes
