---
apiVersion: v1
kind: Service
metadata:
  name: tsds-apache
  labels:
    globalnoc.iu.edu/tool: tsds
    {{ include "tsds.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: tsds-apache
  selector:
    app: tsds-apache
