apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsds-frontend
  labels:
    globalnoc.iu.edu/tool: tsds
    app: tsds-frontend
    {{ include "tsds.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.apache }}
  selector:
    matchLabels:
      app: tsds-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tsds-frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
          
      {{- with .Values.frontend.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
          
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: tsds-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default "latest" }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: 8080tcp
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/nginx/html/tsds-gnui/tsds-config.json
              name: tsds-config
              readOnly: true
              subPath: tsds-config.json
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: tsds-frontend-config
            optional: false
          name: tsds-config