---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tsds-name-service-config
  labels:
    {{ include "tsds.labels" . | nindent 4 }}
data:
  name_service.xml: |
    <config>
      <cloud id="GlobalNOC">
        <class id="CDS">
          <version value="2">
            <service id="Circuit">
              <location url="{{ .Values.cdsUrl }}/cds2-kerb/circuit.cgi" weight="1"></location>
            </service>
            <service id="Node">
              <location url="{{ .Values.cdsUrl }}/cds2-kerb/node.cgi" weight="1"></location>
            </service>
            <service id="RBAC">
              <location url="{{ .Values.cdsUrl }}/cds2-kerb/rbac.cgi" weight="1"></location>
            </service>
            <service id="Service">
              <location url="{{ .Values.cdsUrl }}/cds2-kerb/service.cgi" weight="1"></location>
            </service>
          </version>
        </class>
        <class id="Session">
          <version value="1">
            <service id="Session">
              <location url="{{ .Values.cdsUrl }}/session/session.cgi" weight="1"></location>
            </service>
          </version>
        </class>
        <class id="TIX">
          <version value="1">
            <service id="Ticketing">
              <location url="{{ .Values.tixUrl }}/tix-basic/tix.cgi" weight="1"></location>
            </service>
          </version>
        </class>
        <class id="TSDS">
          <version value="1">
            <service id="Admin">
              <location url="http://tsds-apache.{{ .Release.Namespace }}.svc.cluster.local/tsds/services/admin.cgi" weight="1"></location>
            </service>
            <service id="Aggregation">
              <location url="http://tsds-apache.{{ .Release.Namespace }}.svc.cluster.local/tsds/services/aggregation.cgi" weight="1"></location>
            </service>
            <service id="Atlas">
              <location url="http://tsds-apache.{{ .Release.Namespace }}.svc.cluster.local/tsds/services/atlas.cgi" weight="1"></location>
            </service>
            <service id="Forge">
              <location url="http://tsds-apache.{{ .Release.Namespace }}.svc.cluster.local/tsds/services/forge.cgi" weight="1"></location>
            </service>
            <service id="Image">
              <location url="http://tsds-apache.{{ .Release.Namespace }}.svc.cluster.local/tsds/services/image.cgi" weight="1"></location>
            </service>
            <service id="Metadata">
              <location url="http://tsds-apache.{{ .Release.Namespace }}.svc.cluster.local/tsds/services/metadata.cgi" weight="1"></location>
            </service>
            <service id="Push">
              <location url="http://tsds-apache.{{ .Release.Namespace }}.svc.cluster.local/tsds/services/push.cgi" weight="1"></location>
            </service>
            <service id="Query">
              <location url="http://tsds-apache.{{ .Release.Namespace }}.svc.cluster.local/tsds/services/query.cgi" weight="1"></location>
            </service>
            <service id="Report">
              <location url="http://tsds-apache.{{ .Release.Namespace }}.svc.cluster.local/tsds/services/report.cgi" weight="1"></location>
            </service>
            <service id="Search">
              <location url="http://tsds-apache.{{ .Release.Namespace }}.svc.cluster.local/tsds/services/search.cgi" weight="1"></location>
            </service>
          </version>
        </class>
      </cloud>
    </config>
