---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tsds-logging
  labels:
    {{ include "tsds.labels" . | nindent 4 }}
data:
  logging.conf: |
    log4perl.rootLogger = DEBUG, SCREEN
    log4perl.appender.SCREEN = Log::Dispatch::Screen
    log4perl.appender.SCREEN.min_level = debug
    log4perl.appender.SCREEN.ident = TSDS
    log4perl.appender.SCREEN.facility = LOCAL0
    log4perl.appender.SCREEN.layout = PatternLayout
    log4perl.appender.SCREEN.layout.ConversionPattern=[%d] %F %L %c - %m%n
