apiVersion: v1
data:
  tsds-config.json: |
    {
      "tsds": {
        "base_url": "https://tsds.{{ .Values.global.domainName }}",
        "services_path": "/tsds/services"
      }
    }
kind: ConfigMap
metadata:
  name: tsds-frontend-config