apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsds-apache
  labels:
    globalnoc.iu.edu/tool: tsds
    app: tsds-apache
    {{ include "tsds.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.apache }}
  selector:
    matchLabels:
      app: tsds-apache
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tsds-apache
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
          
      {{- with .Values.services.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
          
      {{- with .Values.services.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: tsds-apache
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: Always
          volumeMounts:
          
            ####### TSDS Services #######
            - mountPath: /etc/grnoc/tsds/services/logging.conf
              name: tsds-logging
              subPath: logging.conf
            - mountPath: /etc/grnoc/tsds/services/config.xml
              name: tsds-config
              subPath: config.xml
            - mountPath: /etc/grnoc/tsds/services/constraints.xml
              name: tsds-constraints-config
              subPath: constraints.xml

            ####### apache #######
            - mountPath: /etc/httpd/conf.d/grnoc/10-tsds-services.conf
              name: tsds-apache-config
              subPath: tsds-services.conf
            - mountPath: /etc/httpd/conf.d/grnoc/20-tsds-frontend.conf
              name: tsds-apache-config
              subPath: tsds-frontend.conf
            - mountPath: /etc/httpd/conf.d/grnoc/glue.conf
              name: tsds-apache-config
              subPath: glue.conf
            - mountPath: /etc/httpd/conf.d/grnoc/grnoc-proxy.conf
              name: tsds-apache-config
              subPath: grnoc-proxy.conf
            - mountPath: /etc/httpd/conf.d/grnoc/yui.conf
              name: tsds-apache-config
              subPath: yui.conf

            ####### TSDS Proxy/Remote Services #######
            - mountPath: /etc/grnoc/proxy/name_service.xml
              name: tsds-name-service-config
              subPath: name_service.xml
            - mountPath: /etc/grnoc/proxy/remote_service.xml
              name: tsds-remote-service-config
              subPath: remote_service.xml

          command: ["/usr/sbin/httpd", "-D", "FOREGROUND"]
          ports:
            - containerPort: 80
      volumes:
        - name: tsds-config
          secret:
            secretName: tsds-config
        - name: tsds-constraints-config
          configMap:
            items:
              - key: constraints.xml
                path: constraints.xml
            name: tsds-constraints-config
        - name: tsds-logging
          configMap:
            items:
              - key: logging.conf
                path: logging.conf
            name: tsds-logging
        - name: tsds-name-service-config
          configMap:
            items:
              - key: name_service.xml
                path: name_service.xml
            name: tsds-name-service-config
        - name: tsds-remote-service-config
          secret:
            secretName: tsds-remote-service-config
        - name: tsds-apache-config
          configMap:
            items:
              - key: tsds-frontend.conf
                path: tsds-frontend.conf
              - key: tsds-services.conf
                path: tsds-services.conf
              - key: glue.conf
                path: glue.conf
              - key: grnoc-proxy.conf
                path: grnoc-proxy.conf
              - key: yui.conf
                path: yui.conf
            name: tsds-apache-config
