apiVersion: batch/v1
kind: CronJob
metadata:
  name: tsds-expire-cronjob
  labels:
    {{ include "tsds.labels" . | nindent 4 }}
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: 'julius-github'
          containers:
            - name: tsds-expire
              image: "containers.github.grnoc.iu.edu/ndca/tsds-services:latest"
              imagePullPolicy: Always
              command: ["/bin/tsds_expire.pl"]
              volumeMounts:
                - mountPath: /etc/grnoc/tsds/services/logging.conf
                  name: tsds-logging
                  subPath: logging.conf
                - mountPath: /etc/grnoc/tsds/services/config.xml
                  name: tsds-config
                  subPath: config.xml
          volumes:
            - name: tsds-logging
              configMap:
                items:
                  - key: logging.conf
                    path: logging.conf
                name: tsds-logging
            - name: tsds-config
              secret:
                secretName: tsds-config
          restartPolicy: OnFailure
