apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsds-aggregate-daemon
  labels:
    app: tsds-aggregate-daemon
    {{ include "tsds.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsds-aggregate-daemon
  template:
    metadata:
      labels:
        app: tsds-aggregate-daemon
    spec:
      imagePullSecrets:
        - name: 'julius-github'
      containers:
        - name: tsds-aggregate-daemon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/grnoc/tsds/aggregate/logging.conf
              name: tsds-logging
              subPath: logging.conf
            - mountPath: /etc/grnoc/tsds/aggregate/config.xml
              name: tsds-aggregate-config
              subPath: config.xml
          command: ["/usr/bin/tsds_aggregate_daemon.pl", "--nofork"]
      volumes:
        - name: tsds-logging
          configMap:
            items:
              - key: logging.conf
                path: logging.conf
            name: tsds-logging
        - name: tsds-aggregate-config
          secret:
            secretName: tsds-aggregate-config
