apiVersion: v1
kind: Secret
metadata:
  name: tsds-rabbitmq-default-user
data:
  default_user.conf: ZGVmYXVsdF91c2VyID0gZ3Vlc3QKZGVmYXVsdF9wYXNzID0gZ3Vlc3QK
  host: dHNkcy1yYWJiaXRtcS5wYXVjaGFtYi10ZXN0LnN2Yw==
  password: Z3Vlc3QK
  port: NTY3Mg==
  provider: cmFiYml0bXE=
  type: cmFiYml0bXE=
  username: Z3Vlc3QK
