#!/bin/sh
#
# tsds_writer        init file for starting up the tsds writer daemon
#
# chkconfig:   2345 86 14
# description: Starts and stops the tsds writer daemon.

# Source function library.
. /etc/rc.d/init.d/functions

name="tsds_writer"
exec="/usr/bin/$name"
pidfile="/var/run/tsds_writer.pid"
CONFIG="/etc/grnoc/tsds/services/config.xml"

start() {
    [ -f $CONFIG ] || exit 6
    [ -x $exec ] || exit 5
    echo -n $"Starting $name: "
    daemon "$exec --config $CONFIG"
    retval=$?
    echo
    return $retval
}

stop() {
    echo -n $"Stopping $name: "
    if [ -f $pidfile ]
    then
        # shutdown haven't work, try old way
        killproc -p $pidfile $name
        retval=$?
    else
        success "$name shutdown"
    fi
    echo
    return $retval
}

restart() {
    stop
    start
}

rh_status() {
    status -p $pidfile $name
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
exit $?
